### ISSUE TITLE
Deployment and application do not have matching security zones

### ISSUE THREAD

**Issue by dirk2950** [leonreucher/powerpoint-remote-websocket#8]
Does someone have advice how to solve this?
![2024-08-29_152003](https://github.com/user-attachments/assets/992a9387-1d8a-4fe3-bfc5-1d9f443041f3)
Name: 
From: file:///C:/Users/dirkp/Downloads/pptws-v1_0_1_0/pptws-v1_0_1_0/PowerPointWSRemote.vsto

************** Exception Text **************
System.Deployment.Application.InvalidDeploymentException: Deployment and application do not have matching security zones.
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.GetManifests(TimeSpan timeout)
   at Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

**Comment by leonreucher** [comment]
Sure - by reading the readme in the repo ;)

**Comment by leonreucher** [comment]
Installation

Go to the Releases tab and download the latest version. After download the zip archive, make sure to right click the object and go to the file properties. In this window at the bottom check "Unblock" (otherwise you will get errors during the installation).

The last step is to unzip the downloaded file and to run the "installation.bat" script - now just follow the installer instructions.
